### ISSUE TITLE
The template reference '...' is not  valid: could not find template resource or resource copy with this name.

### ISSUE THREAD

**Issue by slavizh** [microsoftgraph/msgraph-bicep-types#126] opened 2024-05-28 11:03 UTC
**Bicep version**
Bicep CLI version 0.27.1 (4b41cb6d4b)

**Resource and API version**
in the reproduction below

**Auth flow**
automated

**Deployment details**
No correlation ID:

```
Error: Code=InvalidTemplate; Message=Deployment template
     | validation failed: 'The template reference 'memberApplications' is not
     | valid: could not find template resource or resource copy with this name.
     | Please see https://aka.ms/arm-function-reference for usage details.'. 
     | The deployment validation failed
```

**Describe the bug**
It should not act this way. I think this is caused by Bicep issue due to how existing resources are referenced in language version 2 which is the one that is compiled if you have Graph resource provider. For Azure resources we can workaround this by using resourceId() function but with graph we can only use existing syntax.
I think it might be related to these two issues:
https://github.com/Azure/bicep/issues/13937
https://github.com/Azure/bicep/issues/12204
https://github.com/Azure/bicep/issues/13555

**To Reproduce**

```bicep
provider microsoftGraph

param entraGroup object = {
  name: 'ExampleGroup2'
  type: 'Security'
  displayName: 'Example Group 2'
  mailNickname: 'exampleGroup2'
  members: [
    {
      name: 'ExampleGroup'
      type: 'Group'
    }
    {
      name: '<some name>'
      resourceGroup: '<some name>'
      type: 'ManagedIdentity'
    }
  ]
}


var defaultMember = {
  subscriptionId: subscription().subscriptionId
  resourceGroup: ''
}

resource memberManagedIdentities 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-07-31-preview' existing = [for (member, i) in entraGroup.members: if (member.type =~ 'ManagedIdentity') {
  name: member.name
  scope: resourceGroup(union(defaultMember, member).subscriptionId, union(defaultMember, member).resourceGroup)
}]

resource memberApplications 'Microsoft.Graph/applications@v1.0' existing = [for (member, i) in entraGroup.members: if (member.type =~ 'Application') {
  uniqueName: member.name
}]

resource memberServicePrincipals 'Microsoft.Graph/servicePrincipals@v1.0' existing = [for (member, i) in entraGroup.members: if (member.type =~ 'Application') {
  appId: memberApplications[i].appId
}]


resource memberGroups 'Microsoft.Graph/groups@v1.0' existing = [for (member, i) in entraGroup.members: if (member.type =~ 'Group') {
  uniqueName: member.name
}]

resource entraGroupRes 'Microsoft.Graph/groups@v1.0' = {
  uniqueName: entraGroup.name
  displayName: entraGroup.displayName
  mailEnabled: false
  mailNickname:  entraGroup.mailNickname
  securityEnabled: entraGroup.securityEnabled
  members: [for (member, i) in entraGroup.members: member.type =~ 'ManagedIdentity'
    ? memberManagedIdentities[i].properties.principalId
    : member.type =~ 'Application'
    ? memberServicePrincipals[i].id
    : member.type =~ 'Group'
    ? memberGroups[i].id
    : ''
  ]
}

```

Strangely even this does not work so it might not be just Bicep issue:

```bicep
provider microsoftGraph

param entraGroup object = {
  name: 'ExampleGroup2'
  type: 'Security'
  displayName: 'Example Group 2'
  mailNickname: 'exampleGroup2'
  members: [
    {
      name: 'ExampleGroup'
      type: 'Group'
    }
  ]
}


resource memberGroups 'Microsoft.Graph/groups@v1.0' existing = [for (member, i) in entraGroup.members: {
  uniqueName: member.name
}]

resource entraGroupRes 'Microsoft.Graph/groups@v1.0' = {
  uniqueName: entraGroup.name
  displayName: entraGroup.displayName
  mailEnabled: false
  mailNickname:  entraGroup.mailNickname
  securityEnabled: entraGroup.securityEnabled
  members: [for (member, i) in entraGroup.members: memberGroups[i].id]
}

```

The only thing that works if you define a single existing group and add it as member. Basically removing being able to add multiple members with for loops.

**Additional context**
N/A

**Comment by dkershaw10** [comment] 2024-05-28 11:48
@jason-dou please investigate if this is a problem in the members/owners implementation, or if it's caused by something in the Bicep implementation.

**Comment by shenglol** [comment] 2024-05-28 23:25
This seems to be related to https://github.com/Azure/bicep/issues/12906.

**Comment by shenglol** [comment] 2024-05-28 23:33
@slavizh One workaround might be to put the existing resource declaration in a nested module, output the id array, and reference them in the parent template.

**Comment by slavizh** [comment] 2024-05-29 06:45
@shenglol can I just say no to that? That is not good workaround. As this is preview it should just be fixed. I have encountered too many issues currently to put it in production so I would rather wait to be fixed. Creating additional deployments increases deployment time and makes the code harder to maintain. Also reduces scale as you cannot go beyond certain number of deployments.

**Comment by dkershaw10** [comment] 2024-05-29 11:06
@slavizh does your second example fail with a different error, or with the same "Template reference is not valid"?

**Comment by slavizh** [comment] 2024-05-29 11:27
@dkershaw10 same just the referenced name is different. As soon as you add loop you get the error. I do not get error if members is empty array but of course than the code is not executed at all.

**Comment by shenglol** [comment] 2024-05-29 19:11
> @slavizh does your second example fail with a different error, or with the same "Template reference is not valid"? Will try to repo myself, later today.

@dkershaw10 Just want to let you know that this highly likely a general ARM deployment engine issue (the issue I linked above), not something specific to the Graph extension. I suggested @jason-dou to transfer the issue to the Bicep repo but GitHub does not support cross-repo transfer.

> @shenglol can I just say no to that? That is not good workaround. As this is preview it should just be fixed. I have encountered too many issues currently to put it in production so I would rather wait to be fixed. Creating additional deployments increases deployment time and makes the code harder to maintain. Also reduces scale as you cannot go beyond certain number of deployments.

@slavizh I understand your concerns. We will make sure this issue gets addressed.

**Comment by slavizh** [comment] 2024-05-31 12:06
@shenglol  there is no workaround to this. I have tried this: https://github.com/microsoftgraph/msgraph-bicep-types/issues/131
where I loop over deployment and basically have the same definitions for existing resource but the existing resources are single one not loops and I got the error in the issue.

I also have tried with separate template for each resource type:

```
module managedIdentityIds 'resource-id.bicep' = [for (member, i) in entraGroup.members: if (member.type =~ 'ManagedIdentity') {
  name: 'memberManagedIdentityId-${uniqueString(entraGroup.name)}-${i}'
  params: {
    member: member
  }
}]

module applicationIds 'resource-id.bicep' = [for (member, i) in entraGroup.members: if (member.type =~ 'Application') {
  name: 'memberApplicationId-${uniqueString(entraGroup.name)}-${i}'
  params: {
    member: member
  }
}]

module servicePrincipalIds 'resource-id.bicep' = [for (member, i) in entraGroup.members: if (member.type =~ 'ServicePrincipal') {
  name: 'memberServicePrincipalId-${uniqueString(entraGroup.name)}-${i}'
  params: {
    member: member
  }
}]

module groupIds 'resource-id.bicep' = [for (member, i) in entraGroup.members: if (member.type =~ 'Group') {
  name: 'memberGroupId-${uniqueString(entraGroup.name)}-${i}'
  params: {
    member: member
  }
}]
```
but still I get error:

```
{
  "code": "InvalidTemplateDeployment",
  "message": "The template deployment 'memberGroupId-6r7qavqqjkwe4-0' is not valid according to the validation procedure. The tracking id is 'f567f33e-384a-41f4-ac48-cfc48ee34418'. See inner errors for details.",
  "details": [
    {
      "code": "Forbidden",
      "target": "/resources/memberApplication",
      "message": "Insufficient privileges to complete the operation. Graph client request id: c3792df7-232d-432c-99c4-47e162ca423b. Graph request timestamp: Fri, 31 May 2024 11:59:12 GMT."
    },
    {
      "code": "Forbidden",
      "target": "/resources/memberGroup",
      "message": "Insufficient privileges to complete the operation. Graph client request id: 9c065d57-f4c1-493b-8890-3da0752df957. Graph request timestamp: Fri, 31 May 2024 11:59:13 GMT."
    }
  ]
}
```


Most likely this can only work if I am not putting all types into members but each into their own parameter which is nightmare experience for those who will use the template and nightmare experience for those who will maintain it.

**Comment by slavizh** [comment] 2024-05-31 12:33
@shenglol @dkershaw10 I think I have nailed it down to conditions not working at all. If I not mistaken even in v2 they should work to some extent so may be the issue is a mix of v2 and graph.

```
provider microsoftGraph

param entraGroup object = {
        name: 'ExampleGroup'
        displayName: 'Example Group 1'
        mailNickname: 'exampleGroup'
      }

var group = {
  name: 'dummy'
  type: ''
}
resource oneMemberGroup 'Microsoft.Graph/groups@v1.0' existing = if (!empty(group.type)) {
  uniqueName: group.name
}

resource entraGroupRes 'Microsoft.Graph/groups@v1.0' = {
  uniqueName: entraGroup.name
  displayName: entraGroup.displayName
  mailEnabled: false
  mailNickname: entraGroup.mailNickname
  securityEnabled: true
  members: !empty(entraGroup.memberGroup.type) ? [
    oneMemberGroup.id
  ] : []
}
```

**Comment by slavizh** [comment] 2024-06-03 06:12
@dkershaw10 I think this should be added as known issues as it is pretty significant to me.

**Comment by shenglol** [comment] 2024-06-14 21:22
> @shenglol @dkershaw10 I think I have nailed it down to conditions not working at all. If I not mistaken even in v2 they should work to some extent so may be the issue is a mix of v2 and graph.
> 
> ```
> provider microsoftGraph
> 
> param entraGroup object = {
>         name: 'ExampleGroup'
>         displayName: 'Example Group 1'
>         mailNickname: 'exampleGroup'
>       }
> 
> var group = {
>   name: 'dummy'
>   type: ''
> }
> resource oneMemberGroup 'Microsoft.Graph/groups@v1.0' existing = if (!empty(group.type)) {
>   uniqueName: group.name
> }
> 
> resource entraGroupRes 'Microsoft.Graph/groups@v1.0' = {
>   uniqueName: entraGroup.name
>   displayName: entraGroup.displayName
>   mailEnabled: false
>   mailNickname: entraGroup.mailNickname
>   securityEnabled: true
>   members: (!empty(group.type) ? [
>     oneMemberGroup.id
>   ] : []
> }
> ```

@slavizh I've identified the root cause for this one. This is due to us performing preflight validation for `oneMemberGroup` while its condition is false. I'm working on a fix for it.

We are still investigating the other issues.

**Comment by shenglol** [comment] 2024-07-17 20:31
Found the bug that blocks the example blow. Working on a fix now.

```
provider microsoftGraph

param entraGroup object = {
  name: 'ExampleGroup2'
  type: 'Security'
  displayName: 'Example Group 2'
  mailNickname: 'exampleGroup2'
  members: [
    {
      name: 'ExampleGroup'
      type: 'Group'
    }
  ]
}


resource memberGroups 'Microsoft.Graph/groups@v1.0' existing = [for (member, i) in entraGroup.members: {
  uniqueName: member.name
}]

resource entraGroupRes 'Microsoft.Graph/groups@v1.0' = {
  uniqueName: entraGroup.name
  displayName: entraGroup.displayName
  mailEnabled: false
  mailNickname:  entraGroup.mailNickname
  securityEnabled: entraGroup.securityEnabled
  members: [for (member, i) in entraGroup.members: memberGroups[i].id]
}
```

**Comment by prittelm** [comment] 2024-09-10 16:15
@shenglol Do you have any updates on this? We are currently running into a very similar issue with the "existing" keyword.

**Comment by shenglol** [comment] 2024-09-16 17:04
> Found the bug that blocks the example blow. Working on a fix now.
> 
> ```
> provider microsoftGraph
> 
> param entraGroup object = {
>   name: 'ExampleGroup2'
>   type: 'Security'
>   displayName: 'Example Group 2'
>   mailNickname: 'exampleGroup2'
>   members: [
>     {
>       name: 'ExampleGroup'
>       type: 'Group'
>     }
>   ]
> }
> 
> 
> resource memberGroups 'Microsoft.Graph/groups@v1.0' existing = [for (member, i) in entraGroup.members: {
>   uniqueName: member.name
> }]
> 
> resource entraGroupRes 'Microsoft.Graph/groups@v1.0' = {
>   uniqueName: entraGroup.name
>   displayName: entraGroup.displayName
>   mailEnabled: false
>   mailNickname:  entraGroup.mailNickname
>   securityEnabled: entraGroup.securityEnabled
>   members: [for (member, i) in entraGroup.members: memberGroups[i].id]
> }
> ```

The fix for this should be deployed recently.

@prittelm Do you mind sharing your code? I wonder if it's the same issue or a different issue.

@slavizh Could you check if this works for you now?

**Comment by slavizh** [comment] 2024-09-18 11:31
@shenglol I can confirm that it works now. Thank you a lot Shenglong! This was one of the critical bugs for us. Unfortunately I think I have encountered another two bugs:
- if you have the same user assigned identity that you want to put into owners and members at the same time you will get an error like:  'The resource 'Microsoft.ManagedIdentity/userAssignedIdentities/<name>' at line '1' and column '2018' is defined multiple times in a template.' This is due to the same identity is defined twice via existing syntax and language version 2 is used when extension microsoftGraph is defined. I beleive this is known Bicep issue with language version 2. If it was Azure resource you could somehow skip using language version 2 by not defining types in your template but with Graph resource it is not possible as adding extension microsoftGraph automatically sets to using language version 2. Note  that I do not know if this issue appears for Graph resources as groups are only supported as members and not owners and the second issue I had was with adding applications/service principals as owners/members which I could not achieve.
- When trying to define existing syntax for applications/service principal upon deployment I get error: {"error":{"code":"Forbidden","target":"/resources/entraGroupRes","message":"Insufficient privileges to complete the operation. Graph client request id: 65974623-5d67-4ee0-9ca9-67f5ce585ae2. Graph request timestamp: 2024-09-18T11:14:34Z."}} (Code:DeploymentOperationFailed). The SP I use for deployment is global administrator so permissions should be ok. I even try getting only the service principal within existing syntax by providing the appId but the same error occurs. Obviously just providing principalId without using existing syntax works.

Should I log separate issues for problem 1 or not?
Should I log separate issue for problem 2 or not?

**Comment by slavizh** [comment] 2024-09-18 11:51
@shenglol another interesting behavior is that if you try to add the same Entra group twice in single deployment by defining it existing loop syntax you also get Insufficient privileges error. Overall that scenario is something someone would do as it does not makes sense to add the same group twice in members but the error message is not correct. For example if you try that scenario with user assigned identity you get error that the resource is defined multiple times.

**Comment by dkershaw10** [comment] 2024-09-18 17:03
@slavizh Thanks for validating the fix, and please can you log separate issues for 1 and 2.  I'm not sure I fully follow issue 2, but if you create a new issue with repro steps then I'm sure I'll understand :).

Doe the "interesting behavior", can you provide error message for insufficient privileges (when adding the same group twice in members please)?  I'll try to repro that as well.  Seems like this might be issue 3 ;)

**Comment by dkershaw10** [comment] 2024-09-20 15:42
Given the other 2 issues, can we close this issue now @slavizh?

**Comment by slavizh** [comment] 2024-09-23 12:40
@dkershaw10 yes

**Closed** 2024-09-23 13:34 UTC
Labels: bug, triaged
